environment:
  matrix:
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  VSI_COMMON_IS_POWERSHELL: 1

clone_script:
  - bash -lc "git clone -q --branch=$APPVEYOR_REPO_BRANCH https://github.com/${APPVEYOR_REPO_NAME}.git $APPVEYOR_BUILD_FOLDER"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && git checkout -qf $APPVEYOR_REPO_BRANCH"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER && git submodule update --init --recursive"

install:
  # update mysy2
  - C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S autoconf automake bison flex"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S git"
  - C:\msys64\usr\bin\bash -lc "cat ~/.bashrc ~/.bash_profile"
  - C:\Python37-x64\Scripts\pip install pyinstaller

# This is how you select "Script mode" instead of "MSBuild" mode. There MUST
# be something in build_script, else it doesn't count :(
build_script:
  - bash -c "cd $APPVEYOR_BUILD_FOLDER && source setup.env && just --wrap C:\\Python37-x64\\Scripts\\pyinstaller .\\build\\just-windows just.spec"

test_script:
  # tests/optionaltest and tests/shtest fail on Windows; run them
  # anyways but ignore their failures.  Also, trace shtest.
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - bash -c "cd $APPVEYOR_BUILD_FOLDER && source setup.env && just test"
