version: "2.4"

services:
  makeself:
    build:
      context: .
      dockerfile: docker/makeself.Dockerfile
      args:
        - MAKESELF_VERSION=${JUST_MAKESELF_VERSION}
    # prevent different users from clobbering each others images
    image: ${JUST_DOCKER_REPO}:makeself
    environment:
      # Variables for docker_entrypoint.bsh
      DOCKER_UID: ${JUST_UID}
      DOCKER_GIDS: ${JUST_GIDS}
      DOCKER_GROUP_NAMES: ${JUST_GROUP_NAMES}
      DOCKER_USERNAME: user
    volumes:
      - type: bind
        source: ${JUST_SOURCE_DIR}
        target: ${JUST_SOURCE_DIR_DOCKER}
    platform: linux
