version: "2.4"

services:
  linux: &linux_anchor
    build:
      context: .
      dockerfile: docker/linux.Dockerfile
    # prevent different users from clobbering each others images
    image: ${JUST_DOCKER_REPO}:linux
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_UID=${JUST_UID}
      - DOCKER_GIDS=${JUST_GIDS}
      - DOCKER_GROUP_NAMES=${JUST_GROUP_NAMES}
      - DOCKER_USERNAME=user
    volumes:
      - type: bind
        source: ${JUST_SOURCE_DIR}
        target: ${JUST_SOURCE_DIR_DOCKER}
    platform: linux
  windows:
    build:
      context: .
      dockerfile: docker/windows.Dockerfile
    image: ${JUST_DOCKER_REPO}:windows
    platform: windows
    volumes:
      - type: bind
        source: ${JUST_SOURCE_DIR}
        target: ${JUST_SOURCE_DIR_DOCKER}
    platform: linux
