version: '3.2'

services:
  vsi:
    image: vsiri/vsi_common
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
  robodoc:
    image: andyneff/robodoc:latest
    volumes:
      - "${SRC_DIR}:/src"
      - "${DOC_DIR}:/doc"
    command: ['--rc', '/src/robodoc.rc']